name: Nightly Test Run
on:
  schedule:
    - cron: "0 2 * * *"   # 2:00 AM UTC
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt pytest
      - run: pytest -q
