name: Nightly Test Run
on:
  schedule:
    - cron: '10 19 * * *'  # Runs every day at 19:10 UTC (6:26 PM)
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt pytest
      - run: pytest -q
